# Generated by Django 3.2.6 on 2021-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
